root: true
extends: vue
env:
  es6: true
  browser: true
parserOptions:
  ecmaVersion: 6
  allowImportExportEverywhere: false
globals:
  $: true
  Pusher: true
  # window: true
  require: true
  CSRF_TOKEN: true
rules:
  indent:
    - 1
    - 4
  quotes:
    - 1
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 1
    - always
  no-undef:
    - 1
  space-before-function-paren:
    - 0
  array-bracket-spacing:
    - 0
  one-var:
    - 1
    - never
  prefer-const:
    - 0
  comma-dangle:
    - 2
    - only-multiline
  padded-blocks:
    - 0
